### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by KhalilJouaneh** [SharkyFi/client#2]
I'm getting this error when I call the fetchAllHistoryLoans function. Can someone tell me how to solve this pesky bug?

`Access to fetch at 'https://sharky.fi/api/loan/my-loans lender=9pKp8XytkmSvGQjmABpDGFxffJfT5XZP6msdWgeWvVCC&network=mainnet&deployEnvironment=production&offset=0&cacheBust=0.2898682646723263' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by KhalilJouaneh** [comment]
![sharyfi_auth_key_request](https://user-images.githubusercontent.com/72300400/218340644-c4087c33-8590-4c52-8b1c-cc6c23a0b470.png)

**Comment by phoenixeliot** [comment]
Yes, because of the expensive nature of this endpoint (it fetches a LOT of data from our database if used improperly, like if you just fetch everything on loop), we can't just open this up to the public. If you need an API key for this, please open a support ticket on our discord (https://discord.gg/sharkyfi) describing your use-case so we can decide on whether to give you one.
